version: '3.7'

services:
  personregistry:
    image: ${DOCKER_REGISTRY-}personregistry
    build:
      context: .
      dockerfile: PersonRegistry/Dockerfile
    ports:
        - "8000:80"
    depends_on:
        - sql_server

  sql_server:
    build:
      dockerfile: mssql_database/Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=the_password123
      - MSSQL_PID=Express
    ports:
        - "1433:1433"

    volumes:
      - sql_server:/var/opt/mssql

volumes:
    sql_server: